<a href="https://colab.research.google.com/github/thakurakanksha288/AI-ASSIGNMENT-PYTHON-/blob/main/assignment2_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##numpy library##


#making an array
import numpy as np
array=np.array([1,2,3,5,4])
print(array)
print(type(array))


#2d array
arr=np.array([[1,2,3],[5,6,4]])
print(arr)

#3d array
a=np.array([[[1,2,3],[5,2,3]], [[5,6,9],[1,5,6]]])

#numpy function

print(a.ndim)
print(arr[1,2])
print(arr[:4])
print(arr.shape)
n=np.array([1,5,3,5])
newarr=n.reshape(2,2)
print(newarr)
newr=arr.reshape(-1)
print(newr)


#nditer() printing each item of the array
for x in np.nditer(a):
  print(x)


#for the index of the array
for idx,x in np.ndenumerate(arr):
  print(idx,x)


#for concatenating two array(same size of the array is must)
r=np.concatenate((n,array))
print(r)

#for joining we use stack

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr3=np.stack((arr1,arr2),axis=1)
print(arr3)

#along horizontal axis
arr4=np.hstack((arr1,arr2))
print(arr4)

#for spliting two array
arr5=np.array_split(arr,4)
print(arr5)

#for sereaching two arrays
y=np.where(arr==4)
print(y)

#for a sorted array
z=np.searchsorted(array,7)
print(z)

#for sorting an array

c=np.sort(arr)
print(c)

[1 2 3 5 4]
<class 'numpy.ndarray'>
[[1 2 3]
 [5 6 4]]
3
4
[[1 2 3]
 [5 6 4]]
(2, 3)
[[1 5]
 [3 5]]
[1 2 3 5 6 4]
1
2
3
5
2
3
5
6
9
1
5
6
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 5
(1, 1) 6
(1, 2) 4
[1 5 3 5 1 2 3 5 4]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[array([[1, 2, 3]]), array([[5, 6, 4]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]
(array([1]), array([2]))
5
[[1 2 3]
 [4 5 6]]


In [7]:
#USING RANDOM FROM NUMPY

import numpy as np
from numpy import random

#print any random value
x=random.randint(100)
print(x)

#for printing a float number
y=random.rand(5)
print(y)#the value is always bewtween zero and one

#for making a random array (1-d)

z=random.randint(100,size=(2))
print(z)

#for making (2-d)array
a=random.randint(100,size=(2,2))
print(a)

#for choicing a number for a certain array
b=np.array([1,2,3,4])
print(b)
c=random.choice(b)
print(c)


#for data distribution
#used in stats and data science

d=random.choice([1,2,3,4],p=[0.1,0.6,0.3,0.0],size=(100))
print(d)


#shuffle an array

print(random.shuffle(b))



56
[0.21949189 0.11545006 0.55049704 0.34793429 0.98384212]
[ 2 37]
[[86 18]
 [89 64]]
[1 2 3 4]
3
[3 3 3 2 2 3 2 3 2 2 1 3 2 3 1 1 3 3 2 2 2 2 2 2 2 3 2 3 1 2 3 3 3 2 3 2 2
 2 2 2 2 2 2 2 2 3 2 3 2 2 2 2 3 2 3 3 3 2 2 2 2 1 2 2 2 2 2 1 3 2 3 2 2 1
 3 2 3 2 3 2 2 3 3 2 3 3 2 2 3 1 2 2 2 2 3 2 2 2 2 3]
None
